### ISSUE TITLE
command completion should support Zsh and PowerShell

### ISSUE THREAD

**Issue by Didier-Lalli** [HewlettPackard/hpecli#104]
Right now it supports only bash

**Comment by reddypramod85** [comment]
./hpe autocompletion --help
Generates a shell completion script for hpe CLI.

        NOTE: The current version supports Bash, ZShell, and PowerShell.

        By default, the sh|zsh|ps file(s) will be generated in the current folder

        Add `--completionfile=/path/to/file` flag to set alternative
        file-path and name.

        Add the generated autocomplete.sh content to user ~/bash_profile file and reload the terminal
        or just source the .sh file directly:
