### ISSUE TITLE
Commands should display host from context with each response

### ISSUE THREAD

**Issue by Didier-Lalli** [HewlettPackard/hpecli#42]
The Oneview plugin displays the information about which host it connects to but iLO doesn't. All should I guess.

**$ hpecli oneview get servers | more**
  An updated version of the CLI is available
Retrieving data from: https://xxx
{
  "type": "server-hardware-list-8",
  "category": "server-hardware",
  "count": 21,
  "created": "2020-02-17T16:21:08.932Z",
  "eTag": "1581956468932",

**$ hpecli ilo get serviceroot | more**
  An updated version of the CLI is available
{
  "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
  "@odata.etag": "W/\"641C2622\"",
  "@odata.id": "/redfish/v1/",

**Comment by Didier-Lalli** [comment]
Or we should allow:

hpecli ilo context 

to display context information. Same for OneView and others. In this case we should not display what is the host at each command.

**Comment by bsoutham** [comment]
fixed in PR#63
https://github.com/HewlettPackard/hpecli/commit/79948290a87da1b132ba68c4994657fbea33b126
